// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzcawqzastexqujwbntf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6Y2F3cXphc3RleHF1andibnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjE4MzEsImV4cCI6MjA2MDQ5NzgzMX0.ZJYBIraPp9x8cllNyPnMq1M05PJL1bMQRrJoM_o4f5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);